# alwayse use absolute paths

##### RESOURCES #####
partition: 'tinyq'
mem: '16000'
threads: 1


##### GENERAL #####
annotation: /path/to/enrichment_analysis_annotation.csv
result_path: /path/to/results/
project_name: MyProject

# genome
# human 'hg19' or 'hg38' 
# mouse 'mm9' or 'mm10'
genome: 'hg38'

##### DATABASES #####
# path to local databases as GMT (*.gmt) or JSON (*.json) files with gene symbols!
# GMT databases can be donwloaded from 
#     MSigDB (http://www.gsea-msigdb.org/gsea/msigdb)
#     Enrichr (https://maayanlab.cloud/Enrichr/#libraries)
# JSON example content: { "MyDB_Term1": ["geneA","geneB","geneC"],"MyDB_Term2": ["geneX","geneY","geneZ"]}
local_databases:
    MSigDB_H_C2_CGP: "test/data/c2.cgp.v2023.2.Hs.symbols.gmt"
    MSigDB_H_C2: "test/data/c2.all.v2022.1.Hs.symbols.gmt"
    MyWiki: "test/data/MyWikiPathways_2019_Human.json"

##### TOOLS #####

### GSEApy - ORA Enrichr (Fisher/hypergeometric test) and preranked GSEA based analysis

### GREAT - region-gene association based analysis

# GREAT paramaters
# https://jokergoo.github.io/rGREAT/reference/great.html
great_parameters:
    min_gene_set_size: 0 #default: 5
    mode: "basalPlusExt" # options: 'basalPlusExt', 'twoClosest', 'oneClosest'
    basal_upstream: 5000 # used in 'basalPlusExt' mode
    basal_downstream: 1000 # used in 'basalPlusExt' mode
    extension: 1000000

### LOLA - region overlap based analysis

# LOLA compatible region set databases
# loaded using loadRegionDB() (https://code.databio.org/LOLA/reference/loadRegionDB.html)
# download from the docs or create your own: https://databio.org/regiondb
# pre-cached .RData files are supported by simpleCache
# provide the exact path to the folder containing the collections e.g., "resources/LOLACore/hg38"
lola_databases:
    LOLACore: "resources/LOLACore/hg38"

### Enrichment plot

# tool specific column names for aggregation, plotting & summaries
column_names:
    ORA_GSEApy:
        top_n: 25
        p_value: 'P_value'
        adj_pvalue: 'Adjusted_P_value'
        effect_size: 'Odds_Ratio'
        overlap: 'Overlap'
        term: 'Term'
    preranked_GSEApy:
        top_n: 25
        p_value: 'NOM_p_val'
        adj_pvalue: 'FDR_q_val'
        effect_size: 'NES'
        overlap: 'Tag'
        term: 'Term'
    GREAT:
        top_n: 25
        p_value: "p_value_hyper" # p_value
        adj_pvalue: "p_adjust_hyper" # p_adjust
        effect_size: "fold_enrichment_hyper" # fold_enrichment
        overlap: "observed_region_hits" # observed_gene_hits
        term: "description"
    LOLA:
        top_n: 25
        p_value: "pValue"
        adj_pvalue: "qValue"
        effect_size: "oddsRatio"
        overlap: "support"
        term: "description"

##### AGGREGATE & SUMMARIZE #####

# adjusted p-value threshold per tool to denote statistical significance
adjp_th:
    ORA_GSEApy: 0.05
    preranked_GSEApy: 0.05
    GREAT: 0.01
    LOLA: 0.01

# number of top terms per feature set within each group for all overview plots (adjusted p-value, effect-size and bubble-heatmap)
top_terms_n: 5

# cap for adjusted p-value plotting: -log10(adjusted p-value) > adjp_cap -> adjp_cap
adjp_cap: 4

# cap for odds ratio plotting: abs(log2(odds ratio)) > or_cap -> sign(log2(odds ratio)) * or_cap
or_cap: 5

# cap for  normalized enrichemnt scores (NES) abs(nes) > nes_cap -> sign(nes) * nes_cap
# applicable only to preranked_GSEApy
nes_cap: 5

# hierarchical cluster flag for summary plots (0=no; 1=yes)
cluster_summary: 0